// @ts-ignore
/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  docs: [
    {
      type: "doc",
      label: "Introduction",
      id: "introduction",
    },
    {
      type: "category",
      label: "Official Extensions",
      collapsed: false,
      items: [
        {
          type: "category",
          label: "aoi.music",
          collapsed: true,
          items: [
            {
              type: "doc",
              label: "Introduction",
              id: "official/aoi.music/aoimusic-introduction",
            },
            {
              type: "category",
              label: "Functions",
              collapsed: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "official/aoi.music/functions",
                },
              ],
            },
          ],
        },
        {
          type: "category",
          label: "aoi.parser",
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "official/aoi.parser",
            },
          ],
        },
        {
          type: "category",
          label: "aoi.panel",
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "official/aoi.panel",
            },
          ],
        },
        {
          type: "category",
          label: "aoi.db",
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "official/aoi.db",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Community Extensions",
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "community",
        },
      ],
    },
  ],
};
